Results of doctest builder run on 2023-01-25 10:28:46
=====================================================

Document: usage
---------------
**********************************************************************
File "usage.rst", line 49, in default
Failed example:
    import lumache
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\essen\AppData\Local\Programs\Python\Python310\lib\doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[0]>", line 1, in <module>
        import lumache
    ModuleNotFoundError: No module named 'lumache'
**********************************************************************
File "usage.rst", line 50, in default
Failed example:
    lumache.get_random_ingredients()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\essen\AppData\Local\Programs\Python\Python310\lib\doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest default[1]>", line 1, in <module>
        lumache.get_random_ingredients()
    NameError: name 'lumache' is not defined
**********************************************************************
1 items had failures:
   2 of   2 in default
2 tests in 1 items.
0 passed and 2 failed.
***Test Failed*** 2 failures.

Doctest summary
===============
    2 tests
    2 failures in tests
    0 failures in setup code
    0 failures in cleanup code
